chores_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('do_your_chores.urls')),
    path('admin/', admin.site.urls),
]

do_your_chores/urls.py
from django.urls import path 
from .views import ChoreBoard, NewHousehold, HouseholdDetail, NewMember, MemberDetail, NewTask, TaskDetail 

app_name = 'chores'
urlpatterns = [
    path('', ChoreBoard.as_view(), name='chores_board'),
    path('house/new', NewHousehold.as_view(), name='new_house'),
    path('house/<int:pk>', HouseholdDetail.as_view(), name='house_detail'),
    path('member/new', NewMember.as_view(), name='new_member'),
    path('member/<int:pk>', MemberDetail.as_view(), name='member_detail'),
    path('task/new', NewTask.as_view(), name='new_task'),
    path('task/<int:pk>', TaskDetail.as_view(), name='task_detail'),
    ]

do_your_chores/models.py
from django.db import models
from django.urls import reverse


class NameField(models.Model):
    name = models.CharField(max_length=32)

    class Meta:
        abstract = True

    def __str__(self):
       return f'{self.name}'


class DayField(models.Model):

    class DaysOfWeek(models.IntegerChoices):
        monday = 1, 'Monday'
        tuesday = 2, 'Tuesday'
        wednesday = 3, 'Wednesday'
        thursday = 4, 'Thursday'
        friday = 5, 'Friday'
        saturday = 6, 'Saturday'
        sunday = 7, 'Sunday'

    day = models.PositiveSmallIntegerField(
            choices=DaysOfWeek.choices, null=True, blank=True
            )

    class Meta:
        abstract = True

    def __str__(self):
        return f'{self.day}'


class FrequencyField(models.Model):
    
    class TaskFrequency(models.IntegerChoices):
        daily = 1, 'daily'
        weekly = 2, 'weekly'

    frequency = models.PositiveSmallIntegerField(
            choices=TaskFrequency.choices,default=TaskFrequency.daily
            )

    class Meta:
        abstract = True


class Week(models.Model):

    class Meta:
        get_latest_by = 'pk'


class Day(DayField):
    week = models.ForeignKey(Week, on_delete=models.CASCADE)


class Household(NameField):

    def get_absolute_url(self):
        return reverse('chores:household_detail', args=[self.pk])#slugify


class Member(NameField):
    house = models.ForeignKey(Household, on_delete=models.CASCADE)
    slack_memberid = models.CharField(max_length=24)

    def get_absolute_url(self):
        return reverse('chores:member_detail', args=[self.pk])


class TaskList(NameField,DayField,FrequencyField):

    def get_absolute_url(self):
        return reverse('chores:task_detail', args=[self.pk])


class AssignedTask(NameField,FrequencyField):
    owner = models.ForeignKey(
            Member, on_delete=models.CASCADE, null=True, blank=True
            )
    day = models.ForeignKey(
            Day, on_delete=models.CASCADE, null=True, blank=True
            )
    is_complete = models.BooleanField()

do_your_chores/views.py
import datetime

from django.shortcuts import render
from django.views.generic.edit import View, CreateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy

from .models import Household, Member, TaskList, Week, Day, AssignedTask


class ChoreBoard(View):

    def get(self, request):
        this_week = Week.objects.latest()
        today_iso = datetime.date.today().isoweekday()#TODO this code exists in two spots
        today = Day.objects.get(day=today_iso,week=this_week)
        todays_chores = AssignedTask.objects.filter(
                day__week=this_week,day=today
                )
        context = {'todays_chores':todays_chores}
        return render(request, 'do_your_chores/chores_board.html', context)


class NewHousehold(CreateView):
    model = Household
    fields = ['name']
    success_url = '/member/new'


class NewMember(CreateView):
    model = Member
    fields = ['house', 'name']

class NewTask(CreateView):
    model = TaskList
    fields = ['name', 'day', 'frequency']

#    def get_success_url(self):
#        back_to_house = self.object.owner.house.pk
#        return reverse_lazy('chores:household_detail', args=[back_to_house])
#    success_url = '/house/1' #make this fella dynamic af

class HouseholdDetail(DetailView):
    model = Household

class MemberDetail(DetailView):
    model = Member

class TaskDetail(DetailView):
    model = TaskList

class DeleteHousehold(DeleteView):
    model = Household
    success_url = '/'

class DeleteMember(DeleteView):
    model = Member
    success_url = '/'

class DeleteTask(DeleteView):
    model = TaskList
    success_url = '/'

do_your_chores/templates/do_your_chores/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'do_your_chores/css/style.css' %}">

    <title>Weekly Chore Board</title>
  </head>
  <body>
    {% include 'do_your_chores/navbar.html' %}

    {% block content %}
    {% endblock %}
      
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/web-animations/2.3.2/web-animations.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/muuri/0.9.5/muuri.min.js"></script>
      <script src="https://unpkg.com/htmx.org@1.7.0" integrity="sha384-EzBXYPt0/T6gxNp0nuPtLkmRpmDBbjg6WmCUZRLXBBwYYmwAUxzlSGej0ARHX0Bo" crossorigin="anonymous"></script>
      <script src="{% static 'do_your_chores/js/chore_board.js' %}"></script>
  </body>
</html>

do_your_chores/templates/do_your_chores/chores_board.html
{% extends 'do_your_chores/base.html' %}

	{% block content %}
<h1 class="text-center">Today's Chores</h1>
<div class="drag-container"></div>
<div class="board">
  <div class="board-column todo">
    <div class="board-column-container">
      <div class="board-column-header">To do</div>
      <div class="board-column-content-wrapper">
        <div class="board-column-content">
	{% for chore in todays_chores %}
	<div class="board-item"><div class="board-item-content"><span>{{ chore.name }}</span></div></div>
	{% endfor %}
        </div>
      </div>
    </div>
  </div>
  <div class="board-column working">
    <div class="board-column-container">
      <div class="board-column-header">In Progress</div>
      <div class="board-column-content-wrapper">
        <div class="board-column-content">
          <div class="board-item"><div class="board-item-content"><span>Item #</span>6</div></div>
          <div class="board-item"><div class="board-item-content"><span>Item #</span>7</div></div>
          <div class="board-item"><div class="board-item-content"><span>Item #</span>8</div></div>
          <div class="board-item"><div class="board-item-content"><span>Item #</span>9</div></div>
          <div class="board-item"><div class="board-item-content"><span>Item #</span>10</div></div>
        </div>
      </div>
    </div>
  </div>
  <div class="board-column done">
    <div class="board-column-container">
      <div class="board-column-header">Done</div>
      <div class="board-column-content-wrapper">
        <div class="board-column-content">
          <div class="board-item"><div class="board-item-content"><span>Item #</span>11</div></div>
          <div class="board-item"><div class="board-item-content"><span>Item #</span>12</div></div>
          <div class="board-item"><div class="board-item-content"><span>Item #</span>13</div></div>
          <div class="board-item"><div class="board-item-content"><span>Item #</span>14</div></div>
          <div class="board-item"><div class="board-item-content"><span>Item #</span>15</div></div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

do_your_chores/templates/do_your_chores/household_confirm_delete.html
{% extends 'do_your_chores/base.html' %}

	{% block content %}
		<form method="post">{% csrf_token %}
		    <p>Are you sure you want to delete "{{ object }}"?</p>
		    <input type="submit" value="Confirm">
		</form>
	{% endblock %}

do_your_chores/templates/do_your_chores/household_detail.html
{% extends 'do_your_chores/base.html' %}

	{% block content %}
		<a class="btn btn-danger" href="{% url 'chores:delete_household' object.id %}">Delete</a></td>
	{% endblock %}

do_your_chores/templates/do_your_chores/household_form.html
{% extends 'do_your_chores/base.html' %}
  
        {% block content %}
                        <form  method="POST">
                                {% csrf_token %}
                                {{ form }}
				<button type="submit" class="btn btn-primary">Create</button>
                        </form>
        {% endblock %}

do_your_chores/templates/do_your_chores/member_confirm_delete.html
{% extends 'do_your_chores/base.html' %}

	{% block content %}
		<form method="post">{% csrf_token %}
		    <p>Are you sure you want to delete "{{ object }}"?</p>
		    <input type="submit" value="Confirm">
		</form>
	{% endblock %}

do_your_chores/templates/do_your_chores/member_detail.html
{% extends 'do_your_chores/base.html' %}

	{% block content %}
		<a class="btn btn-danger" href="{% url 'chores:delete_member' object.id %}">Delete</a></td>
	{% endblock %}

do_your_chores/templates/do_your_chores/member_form.html
{% extends 'do_your_chores/base.html' %}
  
        {% block content %}
                        <form  method="POST">
                                {% csrf_token %}
                                {{ form }}
				<button type="submit" class="btn btn-primary">Create</button>
                        </form>
        {% endblock %}

do_your_chores/templates/do_your_chores/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Do Your Chores</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
		<a class="nav-link active" aria-current="page" href="{% url 'chores:chores_board' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

do_your_chores/templates/do_your_chores/new_chore.html
{% extends 'do_your_chores/base.html' %}
  
        {% block page_content %}

        {% endblock %}

do_your_chores/templates/do_your_chores/task_confirm_delete.html
{% extends 'do_your_chores/base.html' %}

	{% block content %}
		<form method="post">{% csrf_token %}
		    <p>Are you sure you want to delete "{{ object }}"?</p>
		    <input type="submit" value="Confirm">
		</form>
	{% endblock %}

do_your_chores/templates/do_your_chores/task_detail.html
{% extends 'do_your_chores/base.html' %}

	{% block content %}
		<a class="btn btn-danger" href="{% url 'chores:delete_task' object.id %}">Delete</a></td>
	{% endblock %}

do_your_chores/templates/do_your_chores/task_form.html
{% extends 'do_your_chores/base.html' %}
  
        {% block content %}
                        <form  method="POST">
                                {% csrf_token %}
                                {{ form }}
				<button type="submit" class="btn btn-primary">Create</button>
                        </form>
        {% endblock %}

do_your_chores/templates/do_your_chores/tasklist_detail.html
{% extends 'do_your_chores/base.html' %}

	{% block content %}
		<a class="btn btn-danger" href="{% url 'chores:delete_task' object.id %}">Delete</a></td>
	{% endblock %}